export const schema: any = {
  database: 'db-from-json',
  version: 1,
  encrypted: false,
  mode: 'full',
  tables: [
    {
      name: 'fields',
      schema: [
        { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
        { column: 'text', value: 'TEXT NOT NULL' },
      ],
      values: [
        ['Someone fixing their cosplay on the course'],
        ['Meme cosplayer'],
        ['Ahegao hoodie/shirt'],
        ['Bear cosplaying girl'],
        ['Dressed normally but cat ears/tail'],
        ['Dangerously low amount of clothing'],
        ['Dat ass'],
        ['Cosplayer with prop obviously not peace bonded'],
        ['Really shitty wig'],
        ['Someone using a selfie stick'],
        ['Button enthusiast'],
        ['Person carrying a lot of merch of one character'],
        ['Circle of people sitting on the floor playing Switch'],
        ['Idol cosplay group'],
        ['Girl group cosplaying guys from the same show (e.g Haikyuu]'],
        ['"Free Hugs"'],
        ['Someone wearing just a Naruto headband'],
        ['"I think I\'m getting a cold..."'],
        ['Body type of cosplayer and and cosplayed character do not match'],
        ['Non-anime related cosplay'],
        ['Someone doing something inappropriate'],
        ['Someone shouting an old meme'],
        ['Buff guy dressed as girl'],
        ['Fur suit'],
        ['Overpriced food/water'],
        ['Smelly people'],
        ['People with weapons fighting'],
        ['Obligatory Genshin cosplayers'],
        ['Ramune'],
        ['MIKU'],
        ['Shingeki no Kyojin cosplay group'],
        ['Boku no Hero Academia cosplay group'],
        ['Someone carrying a body pillow'],
        ['Deadpool'],
        ['JoJo cosplayer (Pose with them!)'],
        ['Maid outfits'],
        ['Gender swap cosplay'],
        ['Cosplay couple'],
        ['Eeeveelution cosplay'],
        ['It rains'],
        ['Program gets changed/delayed'],
        ['Guy cosplaying Astolfo'],
        ['"My butt/legs/feet hurt"'],
        ['People playing TCG (Yu-Gi-Oh!, MTG, etc.)'],
        ['Lost parents'],
        ['Person that is probably sweating to death in his full body cosplay.'],
        ['20 (or more) meter queue'],
      ],
    },
    {
      name: 'sheets',
      schema: [
        { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
        { column: 'text', value: 'TEXT NOT NULL' },
      ],
    },
    {
      name: 'currentSheet',
      schema: [
        { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
        { column: 'text', value: 'TEXT NOT NULL' },
        { column: 'checked', value: 'INTEGER DEFAULT 0' },
      ],
    },
  ],
};

export const defaultFields: any = {
  database: 'db-from-json',
  version: 1,
  encrypted: false,
  mode: 'partial',
  tables: [
    {
      name: 'fields',
      values: [
        ['Someone fixing their cosplay on the course'],
        ['Meme cosplayer'],
        ['Ahegao hoodie/shirt'],
        ['Bear cosplaying girl'],
        ['Dressed normally but cat ears/tail'],
        ['Dangerously low amount of clothing'],
        ['Dat ass'],
        ['Cosplayer with prop obviously not peace bonded'],
        ['Really shitty wig'],
        ['Someone using a selfie stick'],
        ['Button enthusiast'],
        ['Person carrying a lot of merch of one character'],
        ['Circle of people sitting on the floor playing Switch'],
        ['Idol cosplay group'],
        ['Girl group cosplaying guys from the same show (e.g Haikyuu]'],
        ['"Free Hugs"'],
        ['Someone wearing just a Naruto headband'],
        ['"I think I\'m getting a cold..."'],
        ['Body type of cosplayer and and cosplayed character do not match'],
        ['Non-anime related cosplay'],
        ['Someone doing something inappropriate'],
        ['Someone shouting an old meme'],
        ['Buff guy dressed as girl'],
        ['Fur suit'],
        ['Overpriced food/water'],
        ['Smelly people'],
        ['People with weapons fighting'],
        ['Obligatory Genshin cosplayers'],
        ['Ramune'],
        ['MIKU'],
        ['Shingeki no Kyojin cosplay group'],
        ['Boku no Hero Academia cosplay group'],
        ['Someone carrying a body pillow'],
        ['Deadpool'],
        ['JoJo cosplayer (Pose with them!)'],
        ['Maid outfits'],
        ['Gender swap cosplay'],
        ['Cosplay couple'],
        ['Eeeveelution cosplay'],
        ['It rains'],
        ['Program gets changed/delayed'],
        ['Guy cosplaying Astolfo'],
        ['"My butt/legs/feet hurt"'],
        ['People playing TCG (Yu-Gi-Oh!, MTG, etc.)'],
        ['Lost parents'],
        ['Person that is probably sweating to death in his full body cosplay.'],
        ['20 (or more) meter queue'],
      ],
    },
  ],
};
